name: iox-parquet CI

on: 
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle (snapshot)
        if: ${{ success() && github.ref == 'refs/heads/main'}}
        id: buildSnapshotArtefact
        run: TZ=Europe/Zurich ./gradlew clean build 

      - name: Build with Gradle (stable)
        if: ${{ success() && github.ref == 'refs/heads/stable'}}
        id: buildStableArtefact
        run: TZ=Europe/Zurich ./gradlew clean build -Drelease= 

      - name: Debug 1
        run: |
          ls -la build/libs

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: reports
          path: build/reports/tests/

      - name: Decode
        if: always() && (steps.buildSnapshotArtefact.outcome == 'success' || steps.buildStableArtefact.outcome == 'success')
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/sonatype_upload.gpg.b64
          base64 -d ~/.gradle/sonatype_upload.gpg.b64 > ~/.gradle/sonatype_upload.gpg

      - name: Publish library jar file (snapshot)
        if: ${{ success() && (github.ref == 'refs/heads/main')}}
        run: ./gradlew -i publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype_upload.gpg)
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}} 

      - name: Publish library jar file (stable)
        if: ${{ success() && (github.ref == 'refs/heads/stable')}}
        run: ./gradlew -i -Drelease= publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype_upload.gpg)
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}} 
