name: iox-parquet CI

on: 
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Build with Gradle
        id: buildLib
        run: TZ=Europe/Zurich ./gradlew clean build 

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: reports
          path: build/reports/tests/

      - name: Decode
        #if: ${{ success() }} && github.ref == 'refs/heads/main'
        if: always() && (steps.buildLib.outcome == 'success')
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/sonatype_upload.gpg.b64
          base64 -d ~/.gradle/sonatype_upload.gpg.b64 > ~/.gradle/sonatype_upload.gpg

      # - name: Decode key ring file
      #   if: ${{ success() && github.ref == 'refs/heads/main'}}
      #   run: |
      #     echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/sonatype_upload.gpg.b64
      #     base64 -d ~/.gradle/sonatype_upload.gpg.b64 > ~/.gradle/sonatype_upload.gpg

      - name: Publish library jar file
        if: ${{ success() && github.ref == 'refs/heads/main'}}
        run: ./gradlew -i publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype_upload.gpg)
        env:
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}} 

      # - name: Release cli
      #   run: |
      #     ./gradlew -i app:jreleaserRelease
      #   env:
      #     JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   if: ${{ success() && github.ref == 'refs/heads/main'}}
